/**
 * Global Status Bar Component
 *
 * Displays capacity utilization at the bottom of the customizer,
 * visible across all tabs.
 *
 * @spec openspec/changes/unify-equipment-tab/specs/equipment-tray/spec.md
 */

import React from 'react';

import { AppIcon } from '@/components/ui/AppIcon';

// =============================================================================
// Types
// =============================================================================

export interface StatusBarStats {
  /** Current weight used (tons) */
  weightUsed: number;
  /** Maximum weight (tonnage) */
  weightMax: number;
  /** Weight remaining */
  weightRemaining: number;
  /** Critical slots used */
  slotsUsed: number;
  /** Total critical slots available */
  slotsTotal: number;
  /** Heat generated by weapons */
  heatGenerated: number;
  /** Heat dissipation from heat sinks */
  heatDissipation: number;
}

interface GlobalStatusBarProps {
  /** Status bar statistics */
  stats: StatusBarStats;
  /** Additional CSS classes */
  className?: string;
}

// =============================================================================
// Component
// =============================================================================

/**
 * Global status bar showing weight, slots, and heat capacity
 */
export function GlobalStatusBar({
  stats,
  className = '',
}: GlobalStatusBarProps): React.ReactElement {
  const isOverWeight = stats.weightRemaining < 0;
  const isOverSlots = stats.slotsUsed > stats.slotsTotal;
  const isOverHeat = stats.heatGenerated > stats.heatDissipation;

  return (
    <div
      className={`bg-surface-base border-border-theme-subtle border-t px-4 py-2 ${className}`}
    >
      <div className="flex items-center justify-between gap-6 text-sm">
        {/* Weight */}
        <div className="flex items-center gap-2">
          <span className="text-text-theme-secondary">Weight:</span>
          <span
            className={
              isOverWeight
                ? 'font-medium text-red-400'
                : 'text-text-theme-primary'
            }
          >
            {stats.weightUsed.toFixed(1)} / {stats.weightMax}t
          </span>
          <span
            className={`text-xs ${isOverWeight ? 'text-red-400' : 'text-green-400'}`}
          >
            ({isOverWeight ? '' : '+'}
            {stats.weightRemaining.toFixed(1)}t rem)
          </span>
        </div>

        {/* Divider */}
        <div className="bg-border-theme h-4 w-px" />

        {/* Slots */}
        <div className="flex items-center gap-2">
          <span className="text-text-theme-secondary">Free Slots:</span>
          <span
            className={
              isOverSlots
                ? 'font-medium text-red-400'
                : 'text-text-theme-primary'
            }
          >
            {stats.slotsUsed} / {stats.slotsTotal}
          </span>
          {isOverSlots && (
            <span className="text-xs text-red-400">
              (over by {stats.slotsUsed - stats.slotsTotal})
            </span>
          )}
        </div>

        {/* Divider */}
        <div className="bg-border-theme h-4 w-px" />

        {/* Heat */}
        <div className="flex items-center gap-2">
          <span className="text-text-theme-secondary">Heat:</span>
          <span
            className={
              isOverHeat
                ? 'font-medium text-amber-400'
                : 'text-text-theme-primary'
            }
          >
            {stats.heatGenerated} / {stats.heatDissipation}
          </span>
          {isOverHeat && (
            <span className="text-xs text-amber-400">
              (+{stats.heatGenerated - stats.heatDissipation} buildup)
            </span>
          )}
        </div>

        {/* Spacer to push warnings to right */}
        <div className="flex-1" />

        {/* Capacity warnings */}
        {(isOverWeight || isOverSlots) && (
          <div className="flex items-center gap-2 text-xs">
            <AppIcon name="warning" size="inline" aria-hidden="true" />
            <span className="text-red-400">
              {isOverWeight && 'Over Weight'}
              {isOverWeight && isOverSlots && ' • '}
              {isOverSlots && 'Over Slots'}
            </span>
          </div>
        )}
      </div>
    </div>
  );
}

export default GlobalStatusBar;
