/**
 * Unit Info Banner Component
 * 
 * At-a-glance unit statistics display with "current / max" format
 * for capacity-based stats like MegaMekLab's status bar.
 * 
 * @spec openspec/specs/unit-info-banner/spec.md
 */

import React from 'react';
import { TechBaseBadge } from './TechBaseBadge';
import { ValidationBadge } from './ValidationBadge';
import { TechBase } from '@/types/enums/TechBase';
import { ValidationStatus } from '@/utils/colors/statusColors';

// =============================================================================
// Types
// =============================================================================

export interface UnitStats {
  /** Unit name/variant */
  name: string;
  /** Tonnage (max weight) */
  tonnage: number;
  /** Tech base */
  techBase: TechBase;
  /** Walk MP */
  walkMP: number;
  /** Run MP */
  runMP: number;
  /** Jump MP */
  jumpMP: number;
  /** Current weight used */
  weightUsed: number;
  /** Remaining weight (calculated: tonnage - weightUsed) */
  weightRemaining: number;
  /** Total armor points allocated */
  armorPoints: number;
  /** Maximum armor points possible */
  maxArmorPoints: number;
  /** Critical slots currently used */
  criticalSlotsUsed: number;
  /** Total critical slots available (78 for standard mech) */
  criticalSlotsTotal: number;
  /** Total heat generated by weapons/equipment */
  heatGenerated: number;
  /** Total heat dissipation from heat sinks */
  heatDissipation: number;
  /** Battle Value (optional) */
  battleValue?: number;
  /** Validation status */
  validationStatus: ValidationStatus;
  /** Number of validation errors */
  errorCount: number;
  /** Number of validation warnings */
  warningCount: number;
}

interface UnitInfoBannerProps {
  /** Unit statistics */
  stats: UnitStats;
  /** On reset button click */
  onReset?: () => void;
  /** On debug button click */
  onDebug?: () => void;
  /** Additional CSS classes */
  className?: string;
}

// =============================================================================
// Styles
// =============================================================================

const styles = {
  label: 'text-[10px] font-medium text-slate-400 uppercase tracking-wider',
  value: {
    normal: 'text-white',
    warning: 'text-amber-400',
    error: 'text-red-400',
    success: 'text-green-400',
  },
  muted: 'text-slate-500',
} as const;

// =============================================================================
// Helper Components
// =============================================================================

interface CapacityStatProps {
  label: string;
  current: number | string;
  max: number | string;
  unit?: string;
  status?: 'normal' | 'warning' | 'error' | 'success';
}

/**
 * Displays a stat in "current / max" format with color coding
 */
function CapacityStat({ label, current, max, unit = '', status = 'normal' }: CapacityStatProps) {
  const valueColor = styles.value[status];
  
  return (
    <div className="flex flex-col items-center gap-0.5">
      <span className={styles.label}>{label}</span>
      <div className="flex items-baseline gap-1">
        <span className={`text-lg font-bold ${valueColor}`}>
          {current}{unit}
        </span>
        <span className={styles.muted}>/</span>
        <span className={`text-sm ${styles.muted}`}>
          {max}{unit}
        </span>
      </div>
    </div>
  );
}

interface SimpleStatProps {
  label: string;
  value: number | string;
  status?: 'normal' | 'warning' | 'error' | 'success';
}

/**
 * Displays a simple single-value stat
 */
function SimpleStat({ label, value, status = 'normal' }: SimpleStatProps) {
  const valueColor = styles.value[status];
  
  return (
    <div className="flex flex-col items-center gap-0.5">
      <span className={styles.label}>{label}</span>
      <span className={`text-lg font-bold ${valueColor}`}>{value}</span>
    </div>
  );
}

// =============================================================================
// Main Component
// =============================================================================

/**
 * Unit information banner with stats display in "current / max" format
 */
export function UnitInfoBanner({
  stats,
  onReset,
  onDebug,
  className = '',
}: UnitInfoBannerProps) {
  // Calculate status colors
  const weightStatus: 'normal' | 'warning' | 'error' = 
    stats.weightUsed > stats.tonnage ? 'error' :
    stats.weightRemaining < 0.5 ? 'warning' : 'normal';
  
  const slotsStatus: 'normal' | 'warning' | 'error' = 
    stats.criticalSlotsUsed > stats.criticalSlotsTotal ? 'error' : 'normal';
  
  const heatStatus: 'normal' | 'warning' | 'error' | 'success' = 
    stats.heatGenerated > stats.heatDissipation ? 'error' :
    stats.heatGenerated === stats.heatDissipation ? 'warning' : 'success';
  
  return (
    <div className={`bg-slate-800 border border-slate-700 rounded-lg ${className}`}>
      <div className="flex items-stretch divide-x divide-slate-700">
        {/* Section 1: Identity */}
        <div className="px-4 py-2">
          <div className="flex items-center gap-3">
            <div>
              <h2 className="text-lg font-bold text-white">{stats.name}</h2>
              <div className="flex items-center gap-2 mt-0.5">
                <span className="text-sm text-slate-400">{stats.tonnage} tons</span>
                <TechBaseBadge techBase={stats.techBase} />
              </div>
            </div>
          </div>
        </div>
        
        {/* Section 2: Movement Stats */}
        <div className="px-4 py-2 flex items-center gap-4">
          <SimpleStat label="WALK" value={stats.walkMP} />
          <SimpleStat label="RUN" value={stats.runMP} />
          <SimpleStat label="JUMP" value={stats.jumpMP} />
        </div>
        
        {/* Section 3: Capacity Stats (current / max format) */}
        <div className="flex-1 px-4 py-2 flex items-center justify-around">
          <CapacityStat
            label="WEIGHT"
            current={stats.weightUsed.toFixed(1)}
            max={stats.tonnage.toFixed(1)}
            unit="t"
            status={weightStatus}
          />
          <CapacityStat
            label="ARMOR"
            current={stats.armorPoints}
            max={stats.maxArmorPoints}
            status="normal"
          />
          <CapacityStat
            label="SLOTS"
            current={stats.criticalSlotsUsed}
            max={stats.criticalSlotsTotal}
            status={slotsStatus}
          />
          <CapacityStat
            label="HEAT"
            current={stats.heatGenerated}
            max={stats.heatDissipation}
            status={heatStatus}
          />
        </div>
        
        {/* Section 4: Validation & Actions */}
        <div className="px-4 py-2 flex items-center gap-3">
          <ValidationBadge 
            status={stats.validationStatus}
            label={stats.validationStatus === 'valid' ? 'Valid' : 
                  `${stats.errorCount} errors, ${stats.warningCount} warnings`}
          />
          
          {onReset && (
            <button
              onClick={onReset}
              className="px-3 py-1.5 text-sm bg-slate-700 hover:bg-slate-600 text-slate-300 rounded transition-colors"
            >
              Reset
            </button>
          )}
          {onDebug && (
            <button
              onClick={onDebug}
              className="px-3 py-1.5 text-sm bg-slate-700 hover:bg-slate-600 text-slate-300 rounded transition-colors"
            >
              Debug
            </button>
          )}
        </div>
      </div>
    </div>
  );
}
