/**
 * Equipment Calculations Hook
 * 
 * Computes total weight, critical slots, and heat for mounted equipment.
 * Handles variable equipment calculations through EquipmentCalculatorService.
 * 
 * @spec openspec/specs/equipment-tray/spec.md
 */

import { useMemo } from 'react';
import { 
  IMountedEquipmentInstance, 
  getTotalEquipmentWeight, 
  getTotalEquipmentSlots,
  getEquipmentByCategory,
} from '@/stores/unitState';
import { EquipmentCategory } from '@/types/equipment';

// =============================================================================
// Types
// =============================================================================

/**
 * Category-level equipment statistics
 */
export interface ICategorySummary {
  readonly count: number;
  readonly weight: number;
  readonly slots: number;
  readonly heat: number;
}

/**
 * Complete equipment calculations result
 */
export interface EquipmentCalculations {
  /** Total weight of all equipment in tons */
  readonly totalWeight: number;
  /** Total critical slots used by all equipment */
  readonly totalSlots: number;
  /** Total heat generated by all equipment (weapons) */
  readonly totalHeat: number;
  /** Total number of equipment items */
  readonly itemCount: number;
  /** Count of allocated (placed in locations) items */
  readonly allocatedCount: number;
  /** Count of unallocated (not yet placed) items */
  readonly unallocatedCount: number;
  /** Statistics broken down by equipment category */
  readonly byCategory: Record<EquipmentCategory, ICategorySummary>;
  /** List of unallocated equipment */
  readonly unallocatedEquipment: readonly IMountedEquipmentInstance[];
  /** List of allocated equipment */
  readonly allocatedEquipment: readonly IMountedEquipmentInstance[];
}

// =============================================================================
// Helper Functions
// =============================================================================

/**
 * Create an empty category summary
 */
function createEmptyCategorySummary(): ICategorySummary {
  return {
    count: 0,
    weight: 0,
    slots: 0,
    heat: 0,
  };
}

/**
 * Initialize empty category summaries for all categories
 */
function createEmptyCategorySummaries(): Record<EquipmentCategory, ICategorySummary> {
  const result = {} as Record<EquipmentCategory, ICategorySummary>;
  for (const category of Object.values(EquipmentCategory)) {
    result[category] = createEmptyCategorySummary();
  }
  return result;
}

// =============================================================================
// Hook Implementation
// =============================================================================

/**
 * Hook for calculating equipment totals
 * 
 * Provides total weight, slots, heat, and per-category breakdowns
 * for all equipment mounted on the unit.
 * 
 * @param equipment - Array of mounted equipment instances
 * @returns Complete equipment calculations
 * 
 * @example
 * const equipment = useUnitStore((s) => s.equipment);
 * const calculations = useEquipmentCalculations(equipment);
 * console.log(`Total weight: ${calculations.totalWeight}t`);
 */
export function useEquipmentCalculations(
  equipment: readonly IMountedEquipmentInstance[]
): EquipmentCalculations {
  return useMemo(() => {
    // Separate allocated and unallocated equipment
    const allocatedEquipment = equipment.filter(e => e.location !== undefined);
    const unallocatedEquipment = equipment.filter(e => e.location === undefined);
    
    // Calculate totals
    const totalWeight = getTotalEquipmentWeight(equipment);
    const totalSlots = getTotalEquipmentSlots(equipment);
    const totalHeat = equipment.reduce((total, item) => total + item.heat, 0);
    const itemCount = equipment.length;
    
    // Calculate per-category summaries
    const byCategory = createEmptyCategorySummaries();
    const groupedByCategory = getEquipmentByCategory(equipment);
    
    for (const [category, items] of Object.entries(groupedByCategory)) {
      const categoryKey = category as EquipmentCategory;
      byCategory[categoryKey] = {
        count: items.length,
        weight: items.reduce((sum, item) => sum + item.weight, 0),
        slots: items.reduce((sum, item) => sum + item.criticalSlots, 0),
        heat: items.reduce((sum, item) => sum + item.heat, 0),
      };
    }
    
    return {
      totalWeight,
      totalSlots,
      totalHeat,
      itemCount,
      allocatedCount: allocatedEquipment.length,
      unallocatedCount: unallocatedEquipment.length,
      byCategory,
      unallocatedEquipment,
      allocatedEquipment,
    };
  }, [equipment]);
}

/**
 * Hook for calculating remaining capacity
 * 
 * @param tonnage - Unit's total tonnage
 * @param usedStructuralWeight - Weight used by structural components
 * @param equipment - Array of mounted equipment instances
 * @returns Remaining weight and slots available
 */
export function useRemainingCapacity(
  tonnage: number,
  usedStructuralWeight: number,
  equipment: readonly IMountedEquipmentInstance[]
): { remainingWeight: number; remainingSlots: number } {
  return useMemo(() => {
    const equipmentWeight = getTotalEquipmentWeight(equipment);
    const equipmentSlots = getTotalEquipmentSlots(equipment);
    
    // Total available slots is 78 minus actuators and fixed systems
    // For simplicity, using approximate available slots
    const totalAvailableSlots = 78;
    const systemSlots = 16; // Approximate for actuators
    const availableEquipmentSlots = totalAvailableSlots - systemSlots;
    
    return {
      remainingWeight: Math.max(0, tonnage - usedStructuralWeight - equipmentWeight),
      remainingSlots: Math.max(0, availableEquipmentSlots - equipmentSlots),
    };
  }, [tonnage, usedStructuralWeight, equipment]);
}

export default useEquipmentCalculations;

