/**
 * Ballistic Weapon Definitions
 * 
 * Autocannons, Gauss Rifles, Machine Guns, and ballistic defensive systems.
 * 
 * @spec openspec/specs/weapon-system/spec.md
 */

import { TechBase } from '../../enums/TechBase';
import { RulesLevel } from '../../enums/RulesLevel';
import { IWeapon, WeaponCategory, BallisticWeaponType } from './interfaces';

/**
 * Standard Autocannons
 */
export const AUTOCANNONS: readonly IWeapon[] = [
  {
    id: 'ac-2',
    name: 'AC/2',
    category: WeaponCategory.BALLISTIC,
    subType: BallisticWeaponType.AUTOCANNON,
    techBase: TechBase.INNER_SPHERE,
    rulesLevel: RulesLevel.INTRODUCTORY,
    damage: 2,
    heat: 1,
    ranges: { minimum: 4, short: 8, medium: 16, long: 24 },
    weight: 6,
    criticalSlots: 1,
    ammoPerTon: 45,
    costCBills: 75000,
    battleValue: 37,
    introductionYear: 2290,
  },
  {
    id: 'ac-5',
    name: 'AC/5',
    category: WeaponCategory.BALLISTIC,
    subType: BallisticWeaponType.AUTOCANNON,
    techBase: TechBase.INNER_SPHERE,
    rulesLevel: RulesLevel.INTRODUCTORY,
    damage: 5,
    heat: 1,
    ranges: { minimum: 3, short: 6, medium: 12, long: 18 },
    weight: 8,
    criticalSlots: 4,
    ammoPerTon: 20,
    costCBills: 125000,
    battleValue: 70,
    introductionYear: 2250,
  },
  {
    id: 'ac-10',
    name: 'AC/10',
    category: WeaponCategory.BALLISTIC,
    subType: BallisticWeaponType.AUTOCANNON,
    techBase: TechBase.INNER_SPHERE,
    rulesLevel: RulesLevel.INTRODUCTORY,
    damage: 10,
    heat: 3,
    ranges: { minimum: 0, short: 5, medium: 10, long: 15 },
    weight: 12,
    criticalSlots: 7,
    ammoPerTon: 10,
    costCBills: 200000,
    battleValue: 123,
    introductionYear: 2443,
  },
  {
    id: 'ac-20',
    name: 'AC/20',
    category: WeaponCategory.BALLISTIC,
    subType: BallisticWeaponType.AUTOCANNON,
    techBase: TechBase.INNER_SPHERE,
    rulesLevel: RulesLevel.INTRODUCTORY,
    damage: 20,
    heat: 7,
    ranges: { minimum: 0, short: 3, medium: 6, long: 9 },
    weight: 14,
    criticalSlots: 10,
    ammoPerTon: 5,
    costCBills: 300000,
    battleValue: 178,
    introductionYear: 2500,
  },
] as const;

/**
 * Ultra Autocannons
 */
export const ULTRA_AUTOCANNONS: readonly IWeapon[] = [
  {
    id: 'uac-2',
    name: 'Ultra AC/2',
    category: WeaponCategory.BALLISTIC,
    subType: BallisticWeaponType.ULTRA_AC,
    techBase: TechBase.INNER_SPHERE,
    rulesLevel: RulesLevel.STANDARD,
    damage: 2,
    heat: 1,
    ranges: { minimum: 3, short: 8, medium: 17, long: 25 },
    weight: 7,
    criticalSlots: 3,
    ammoPerTon: 45,
    costCBills: 120000,
    battleValue: 56,
    introductionYear: 3057,
    special: ['Can fire twice'],
  },
  {
    id: 'uac-5',
    name: 'Ultra AC/5',
    category: WeaponCategory.BALLISTIC,
    subType: BallisticWeaponType.ULTRA_AC,
    techBase: TechBase.INNER_SPHERE,
    rulesLevel: RulesLevel.STANDARD,
    damage: 5,
    heat: 1,
    ranges: { minimum: 2, short: 6, medium: 13, long: 20 },
    weight: 9,
    criticalSlots: 5,
    ammoPerTon: 20,
    costCBills: 200000,
    battleValue: 112,
    introductionYear: 3057,
    special: ['Can fire twice'],
  },
  {
    id: 'uac-10',
    name: 'Ultra AC/10',
    category: WeaponCategory.BALLISTIC,
    subType: BallisticWeaponType.ULTRA_AC,
    techBase: TechBase.INNER_SPHERE,
    rulesLevel: RulesLevel.STANDARD,
    damage: 10,
    heat: 4,
    ranges: { minimum: 0, short: 6, medium: 12, long: 18 },
    weight: 13,
    criticalSlots: 7,
    ammoPerTon: 10,
    costCBills: 320000,
    battleValue: 210,
    introductionYear: 3057,
    special: ['Can fire twice'],
  },
  {
    id: 'uac-20',
    name: 'Ultra AC/20',
    category: WeaponCategory.BALLISTIC,
    subType: BallisticWeaponType.ULTRA_AC,
    techBase: TechBase.INNER_SPHERE,
    rulesLevel: RulesLevel.STANDARD,
    damage: 20,
    heat: 8,
    ranges: { minimum: 0, short: 3, medium: 7, long: 10 },
    weight: 15,
    criticalSlots: 10,
    ammoPerTon: 5,
    costCBills: 480000,
    battleValue: 281,
    introductionYear: 3060,
    special: ['Can fire twice'],
  },
  // Clan Ultra ACs
  {
    id: 'clan-uac-2',
    name: 'Ultra AC/2 (Clan)',
    category: WeaponCategory.BALLISTIC,
    subType: BallisticWeaponType.ULTRA_AC,
    techBase: TechBase.CLAN,
    rulesLevel: RulesLevel.STANDARD,
    damage: 2,
    heat: 1,
    ranges: { minimum: 2, short: 9, medium: 18, long: 27 },
    weight: 5,
    criticalSlots: 2,
    ammoPerTon: 45,
    costCBills: 120000,
    battleValue: 62,
    introductionYear: 2827,
    special: ['Can fire twice'],
  },
  {
    id: 'clan-uac-5',
    name: 'Ultra AC/5 (Clan)',
    category: WeaponCategory.BALLISTIC,
    subType: BallisticWeaponType.ULTRA_AC,
    techBase: TechBase.CLAN,
    rulesLevel: RulesLevel.STANDARD,
    damage: 5,
    heat: 1,
    ranges: { minimum: 0, short: 7, medium: 14, long: 21 },
    weight: 7,
    criticalSlots: 3,
    ammoPerTon: 20,
    costCBills: 200000,
    battleValue: 122,
    introductionYear: 2825,
    special: ['Can fire twice'],
  },
  {
    id: 'clan-uac-10',
    name: 'Ultra AC/10 (Clan)',
    category: WeaponCategory.BALLISTIC,
    subType: BallisticWeaponType.ULTRA_AC,
    techBase: TechBase.CLAN,
    rulesLevel: RulesLevel.STANDARD,
    damage: 10,
    heat: 3,
    ranges: { minimum: 0, short: 6, medium: 12, long: 18 },
    weight: 10,
    criticalSlots: 4,
    ammoPerTon: 10,
    costCBills: 320000,
    battleValue: 210,
    introductionYear: 2825,
    special: ['Can fire twice'],
  },
  {
    id: 'clan-uac-20',
    name: 'Ultra AC/20 (Clan)',
    category: WeaponCategory.BALLISTIC,
    subType: BallisticWeaponType.ULTRA_AC,
    techBase: TechBase.CLAN,
    rulesLevel: RulesLevel.STANDARD,
    damage: 20,
    heat: 7,
    ranges: { minimum: 0, short: 4, medium: 8, long: 12 },
    weight: 12,
    criticalSlots: 8,
    ammoPerTon: 5,
    costCBills: 480000,
    battleValue: 335,
    introductionYear: 2825,
    special: ['Can fire twice'],
  },
] as const;

/**
 * LB-X Autocannons
 */
export const LBX_AUTOCANNONS: readonly IWeapon[] = [
  {
    id: 'lb-2-x-ac',
    name: 'LB 2-X AC',
    category: WeaponCategory.BALLISTIC,
    subType: BallisticWeaponType.LB_X_AC,
    techBase: TechBase.INNER_SPHERE,
    rulesLevel: RulesLevel.STANDARD,
    damage: 2,
    heat: 1,
    ranges: { minimum: 4, short: 9, medium: 18, long: 27 },
    weight: 6,
    criticalSlots: 4,
    ammoPerTon: 45,
    costCBills: 150000,
    battleValue: 42,
    introductionYear: 3058,
    special: ['Cluster ammo available'],
  },
  {
    id: 'lb-5-x-ac',
    name: 'LB 5-X AC',
    category: WeaponCategory.BALLISTIC,
    subType: BallisticWeaponType.LB_X_AC,
    techBase: TechBase.INNER_SPHERE,
    rulesLevel: RulesLevel.STANDARD,
    damage: 5,
    heat: 1,
    ranges: { minimum: 3, short: 7, medium: 14, long: 21 },
    weight: 8,
    criticalSlots: 5,
    ammoPerTon: 20,
    costCBills: 250000,
    battleValue: 83,
    introductionYear: 3058,
    special: ['Cluster ammo available'],
  },
  {
    id: 'lb-10-x-ac',
    name: 'LB 10-X AC',
    category: WeaponCategory.BALLISTIC,
    subType: BallisticWeaponType.LB_X_AC,
    techBase: TechBase.INNER_SPHERE,
    rulesLevel: RulesLevel.STANDARD,
    damage: 10,
    heat: 2,
    ranges: { minimum: 0, short: 6, medium: 12, long: 18 },
    weight: 11,
    criticalSlots: 6,
    ammoPerTon: 10,
    costCBills: 400000,
    battleValue: 148,
    introductionYear: 3044,
    special: ['Cluster ammo available'],
  },
  {
    id: 'lb-20-x-ac',
    name: 'LB 20-X AC',
    category: WeaponCategory.BALLISTIC,
    subType: BallisticWeaponType.LB_X_AC,
    techBase: TechBase.INNER_SPHERE,
    rulesLevel: RulesLevel.STANDARD,
    damage: 20,
    heat: 6,
    ranges: { minimum: 0, short: 4, medium: 8, long: 12 },
    weight: 14,
    criticalSlots: 11,
    ammoPerTon: 5,
    costCBills: 600000,
    battleValue: 237,
    introductionYear: 3058,
    special: ['Cluster ammo available'],
  },
  // Clan LB-X
  {
    id: 'clan-lb-2-x-ac',
    name: 'LB 2-X AC (Clan)',
    category: WeaponCategory.BALLISTIC,
    subType: BallisticWeaponType.LB_X_AC,
    techBase: TechBase.CLAN,
    rulesLevel: RulesLevel.STANDARD,
    damage: 2,
    heat: 1,
    ranges: { minimum: 4, short: 10, medium: 20, long: 30 },
    weight: 5,
    criticalSlots: 3,
    ammoPerTon: 45,
    costCBills: 150000,
    battleValue: 47,
    introductionYear: 2826,
    special: ['Cluster ammo available'],
  },
  {
    id: 'clan-lb-5-x-ac',
    name: 'LB 5-X AC (Clan)',
    category: WeaponCategory.BALLISTIC,
    subType: BallisticWeaponType.LB_X_AC,
    techBase: TechBase.CLAN,
    rulesLevel: RulesLevel.STANDARD,
    damage: 5,
    heat: 1,
    ranges: { minimum: 3, short: 8, medium: 15, long: 24 },
    weight: 7,
    criticalSlots: 4,
    ammoPerTon: 20,
    costCBills: 250000,
    battleValue: 93,
    introductionYear: 2825,
    special: ['Cluster ammo available'],
  },
  {
    id: 'clan-lb-10-x-ac',
    name: 'LB 10-X AC (Clan)',
    category: WeaponCategory.BALLISTIC,
    subType: BallisticWeaponType.LB_X_AC,
    techBase: TechBase.CLAN,
    rulesLevel: RulesLevel.STANDARD,
    damage: 10,
    heat: 2,
    ranges: { minimum: 0, short: 6, medium: 12, long: 18 },
    weight: 10,
    criticalSlots: 5,
    ammoPerTon: 10,
    costCBills: 400000,
    battleValue: 148,
    introductionYear: 2595,
    special: ['Cluster ammo available'],
  },
  {
    id: 'clan-lb-20-x-ac',
    name: 'LB 20-X AC (Clan)',
    category: WeaponCategory.BALLISTIC,
    subType: BallisticWeaponType.LB_X_AC,
    techBase: TechBase.CLAN,
    rulesLevel: RulesLevel.STANDARD,
    damage: 20,
    heat: 6,
    ranges: { minimum: 0, short: 4, medium: 8, long: 12 },
    weight: 12,
    criticalSlots: 9,
    ammoPerTon: 5,
    costCBills: 600000,
    battleValue: 237,
    introductionYear: 2826,
    special: ['Cluster ammo available'],
  },
] as const;

/**
 * Rotary Autocannons
 */
export const ROTARY_AUTOCANNONS: readonly IWeapon[] = [
  {
    id: 'rac-2',
    name: 'Rotary AC/2',
    category: WeaponCategory.BALLISTIC,
    subType: BallisticWeaponType.ROTARY_AC,
    techBase: TechBase.INNER_SPHERE,
    rulesLevel: RulesLevel.STANDARD,
    damage: 2,
    heat: 1,
    ranges: { minimum: 0, short: 6, medium: 12, long: 18 },
    weight: 8,
    criticalSlots: 3,
    ammoPerTon: 45,
    costCBills: 175000,
    battleValue: 118,
    introductionYear: 3062,
    special: ['Can fire 1-6 shots'],
  },
  {
    id: 'rac-5',
    name: 'Rotary AC/5',
    category: WeaponCategory.BALLISTIC,
    subType: BallisticWeaponType.ROTARY_AC,
    techBase: TechBase.INNER_SPHERE,
    rulesLevel: RulesLevel.STANDARD,
    damage: 5,
    heat: 1,
    ranges: { minimum: 0, short: 5, medium: 10, long: 15 },
    weight: 10,
    criticalSlots: 6,
    ammoPerTon: 20,
    costCBills: 275000,
    battleValue: 247,
    introductionYear: 3062,
    special: ['Can fire 1-6 shots'],
  },
] as const;

/**
 * Light Autocannons
 */
export const LIGHT_AUTOCANNONS: readonly IWeapon[] = [
  {
    id: 'lac-2',
    name: 'Light AC/2',
    category: WeaponCategory.BALLISTIC,
    subType: BallisticWeaponType.LIGHT_AC,
    techBase: TechBase.INNER_SPHERE,
    rulesLevel: RulesLevel.STANDARD,
    damage: 2,
    heat: 1,
    ranges: { minimum: 0, short: 6, medium: 12, long: 18 },
    weight: 4,
    criticalSlots: 1,
    ammoPerTon: 45,
    costCBills: 100000,
    battleValue: 30,
    introductionYear: 3068,
  },
  {
    id: 'lac-5',
    name: 'Light AC/5',
    category: WeaponCategory.BALLISTIC,
    subType: BallisticWeaponType.LIGHT_AC,
    techBase: TechBase.INNER_SPHERE,
    rulesLevel: RulesLevel.STANDARD,
    damage: 5,
    heat: 1,
    ranges: { minimum: 0, short: 5, medium: 10, long: 15 },
    weight: 5,
    criticalSlots: 2,
    ammoPerTon: 20,
    costCBills: 150000,
    battleValue: 62,
    introductionYear: 3068,
  },
] as const;

/**
 * Gauss Rifles
 */
export const GAUSS_RIFLES: readonly IWeapon[] = [
  {
    id: 'gauss-rifle',
    name: 'Gauss Rifle',
    category: WeaponCategory.BALLISTIC,
    subType: BallisticWeaponType.GAUSS,
    techBase: TechBase.INNER_SPHERE,
    rulesLevel: RulesLevel.STANDARD,
    damage: 15,
    heat: 1,
    ranges: { minimum: 2, short: 7, medium: 15, long: 22 },
    weight: 15,
    criticalSlots: 7,
    ammoPerTon: 8,
    costCBills: 300000,
    battleValue: 320,
    introductionYear: 2590,
    isExplosive: true,
  },
  {
    id: 'light-gauss-rifle',
    name: 'Light Gauss Rifle',
    category: WeaponCategory.BALLISTIC,
    subType: BallisticWeaponType.GAUSS,
    techBase: TechBase.INNER_SPHERE,
    rulesLevel: RulesLevel.STANDARD,
    damage: 8,
    heat: 1,
    ranges: { minimum: 3, short: 8, medium: 17, long: 25 },
    weight: 12,
    criticalSlots: 5,
    ammoPerTon: 16,
    costCBills: 275000,
    battleValue: 159,
    introductionYear: 3056,
    isExplosive: true,
  },
  {
    id: 'heavy-gauss-rifle',
    name: 'Heavy Gauss Rifle',
    category: WeaponCategory.BALLISTIC,
    subType: BallisticWeaponType.GAUSS,
    techBase: TechBase.INNER_SPHERE,
    rulesLevel: RulesLevel.STANDARD,
    damage: 25,
    heat: 2,
    ranges: { minimum: 4, short: 6, medium: 13, long: 20 },
    weight: 18,
    criticalSlots: 11,
    ammoPerTon: 4,
    costCBills: 500000,
    battleValue: 346,
    introductionYear: 3061,
    isExplosive: true,
  },
  {
    id: 'ap-gauss-rifle',
    name: 'AP Gauss Rifle',
    category: WeaponCategory.BALLISTIC,
    subType: BallisticWeaponType.GAUSS,
    techBase: TechBase.CLAN,
    rulesLevel: RulesLevel.STANDARD,
    damage: 3,
    heat: 1,
    ranges: { minimum: 0, short: 3, medium: 6, long: 9 },
    weight: 0.5,
    criticalSlots: 1,
    ammoPerTon: 40,
    costCBills: 10000,
    battleValue: 21,
    introductionYear: 3069,
    isExplosive: true,
  },
  {
    id: 'clan-gauss-rifle',
    name: 'Gauss Rifle (Clan)',
    category: WeaponCategory.BALLISTIC,
    subType: BallisticWeaponType.GAUSS,
    techBase: TechBase.CLAN,
    rulesLevel: RulesLevel.STANDARD,
    damage: 15,
    heat: 1,
    ranges: { minimum: 2, short: 7, medium: 15, long: 22 },
    weight: 12,
    criticalSlots: 6,
    ammoPerTon: 8,
    costCBills: 300000,
    battleValue: 320,
    introductionYear: 2828,
    isExplosive: true,
  },
] as const;

/**
 * Machine Guns
 */
export const MACHINE_GUNS: readonly IWeapon[] = [
  {
    id: 'machine-gun',
    name: 'Machine Gun',
    category: WeaponCategory.BALLISTIC,
    subType: BallisticWeaponType.MACHINE_GUN,
    techBase: TechBase.INNER_SPHERE,
    rulesLevel: RulesLevel.INTRODUCTORY,
    damage: 2,
    heat: 0,
    ranges: { minimum: 0, short: 1, medium: 2, long: 3 },
    weight: 0.5,
    criticalSlots: 1,
    ammoPerTon: 200,
    costCBills: 5000,
    battleValue: 5,
    introductionYear: 1950,
  },
  {
    id: 'light-machine-gun',
    name: 'Light Machine Gun',
    category: WeaponCategory.BALLISTIC,
    subType: BallisticWeaponType.MACHINE_GUN,
    techBase: TechBase.INNER_SPHERE,
    rulesLevel: RulesLevel.STANDARD,
    damage: 1,
    heat: 0,
    ranges: { minimum: 0, short: 2, medium: 4, long: 6 },
    weight: 0.25,
    criticalSlots: 1,
    ammoPerTon: 200,
    costCBills: 5000,
    battleValue: 5,
    introductionYear: 3068,
  },
  {
    id: 'heavy-machine-gun',
    name: 'Heavy Machine Gun',
    category: WeaponCategory.BALLISTIC,
    subType: BallisticWeaponType.MACHINE_GUN,
    techBase: TechBase.INNER_SPHERE,
    rulesLevel: RulesLevel.STANDARD,
    damage: 3,
    heat: 0,
    ranges: { minimum: 0, short: 1, medium: 2, long: 2 },
    weight: 1,
    criticalSlots: 1,
    ammoPerTon: 100,
    costCBills: 7500,
    battleValue: 6,
    introductionYear: 3068,
  },
  {
    id: 'clan-machine-gun',
    name: 'Machine Gun (Clan)',
    category: WeaponCategory.BALLISTIC,
    subType: BallisticWeaponType.MACHINE_GUN,
    techBase: TechBase.CLAN,
    rulesLevel: RulesLevel.STANDARD,
    damage: 2,
    heat: 0,
    ranges: { minimum: 0, short: 1, medium: 2, long: 3 },
    weight: 0.25,
    criticalSlots: 1,
    ammoPerTon: 200,
    costCBills: 5000,
    battleValue: 5,
    introductionYear: 2825,
  },
] as const;

/**
 * Anti-Missile System
 */
export const BALLISTIC_AMS: readonly IWeapon[] = [
  {
    id: 'ams',
    name: 'Anti-Missile System',
    category: WeaponCategory.BALLISTIC,
    subType: BallisticWeaponType.AMS,
    techBase: TechBase.INNER_SPHERE,
    rulesLevel: RulesLevel.STANDARD,
    damage: 0,
    heat: 1,
    ranges: { minimum: 0, short: 1, medium: 1, long: 1 },
    weight: 0.5,
    criticalSlots: 1,
    ammoPerTon: 12,
    costCBills: 100000,
    battleValue: 32,
    introductionYear: 2617,
    special: ['Defensive'],
  },
  {
    id: 'clan-ams',
    name: 'Anti-Missile System (Clan)',
    category: WeaponCategory.BALLISTIC,
    subType: BallisticWeaponType.AMS,
    techBase: TechBase.CLAN,
    rulesLevel: RulesLevel.STANDARD,
    damage: 0,
    heat: 1,
    ranges: { minimum: 0, short: 1, medium: 1, long: 1 },
    weight: 0.5,
    criticalSlots: 1,
    ammoPerTon: 24,
    costCBills: 100000,
    battleValue: 32,
    introductionYear: 2831,
    special: ['Defensive'],
  },
] as const;

/**
 * All ballistic weapons combined
 */
export const BALLISTIC_WEAPONS: readonly IWeapon[] = [
  ...AUTOCANNONS,
  ...ULTRA_AUTOCANNONS,
  ...LBX_AUTOCANNONS,
  ...ROTARY_AUTOCANNONS,
  ...LIGHT_AUTOCANNONS,
  ...GAUSS_RIFLES,
  ...MACHINE_GUNS,
  ...BALLISTIC_AMS,
] as const;

