/**
 * Energy Weapon Definitions
 * 
 * Lasers, PPCs, Flamers, and energy-based defensive systems.
 * 
 * @spec openspec/specs/weapon-system/spec.md
 */

import { TechBase } from '../../enums/TechBase';
import { RulesLevel } from '../../enums/RulesLevel';
import { IWeapon, WeaponCategory, EnergyWeaponType } from './interfaces';

/**
 * Standard Lasers
 */
export const STANDARD_LASERS: readonly IWeapon[] = [
  {
    id: 'small-laser',
    name: 'Small Laser',
    category: WeaponCategory.ENERGY,
    subType: EnergyWeaponType.LASER,
    techBase: TechBase.INNER_SPHERE,
    rulesLevel: RulesLevel.INTRODUCTORY,
    damage: 3,
    heat: 1,
    ranges: { minimum: 0, short: 1, medium: 2, long: 3 },
    weight: 0.5,
    criticalSlots: 1,
    costCBills: 11250,
    battleValue: 9,
    introductionYear: 2300,
  },
  {
    id: 'medium-laser',
    name: 'Medium Laser',
    category: WeaponCategory.ENERGY,
    subType: EnergyWeaponType.LASER,
    techBase: TechBase.INNER_SPHERE,
    rulesLevel: RulesLevel.INTRODUCTORY,
    damage: 5,
    heat: 3,
    ranges: { minimum: 0, short: 3, medium: 6, long: 9 },
    weight: 1,
    criticalSlots: 1,
    costCBills: 40000,
    battleValue: 46,
    introductionYear: 2300,
  },
  {
    id: 'large-laser',
    name: 'Large Laser',
    category: WeaponCategory.ENERGY,
    subType: EnergyWeaponType.LASER,
    techBase: TechBase.INNER_SPHERE,
    rulesLevel: RulesLevel.INTRODUCTORY,
    damage: 8,
    heat: 8,
    ranges: { minimum: 0, short: 5, medium: 10, long: 15 },
    weight: 5,
    criticalSlots: 2,
    costCBills: 100000,
    battleValue: 123,
    introductionYear: 2316,
  },
] as const;

/**
 * Extended Range Lasers
 */
export const ER_LASERS: readonly IWeapon[] = [
  // Inner Sphere ER Lasers
  {
    id: 'er-small-laser',
    name: 'ER Small Laser',
    category: WeaponCategory.ENERGY,
    subType: EnergyWeaponType.ER_LASER,
    techBase: TechBase.INNER_SPHERE,
    rulesLevel: RulesLevel.STANDARD,
    damage: 3,
    heat: 2,
    ranges: { minimum: 0, short: 2, medium: 4, long: 5 },
    weight: 0.5,
    criticalSlots: 1,
    costCBills: 11250,
    battleValue: 17,
    introductionYear: 3058,
  },
  {
    id: 'er-medium-laser',
    name: 'ER Medium Laser',
    category: WeaponCategory.ENERGY,
    subType: EnergyWeaponType.ER_LASER,
    techBase: TechBase.INNER_SPHERE,
    rulesLevel: RulesLevel.STANDARD,
    damage: 5,
    heat: 5,
    ranges: { minimum: 0, short: 4, medium: 8, long: 12 },
    weight: 1,
    criticalSlots: 1,
    costCBills: 80000,
    battleValue: 62,
    introductionYear: 3058,
  },
  {
    id: 'er-large-laser',
    name: 'ER Large Laser',
    category: WeaponCategory.ENERGY,
    subType: EnergyWeaponType.ER_LASER,
    techBase: TechBase.INNER_SPHERE,
    rulesLevel: RulesLevel.STANDARD,
    damage: 8,
    heat: 12,
    ranges: { minimum: 0, short: 7, medium: 14, long: 19 },
    weight: 5,
    criticalSlots: 2,
    costCBills: 200000,
    battleValue: 163,
    introductionYear: 3037,
  },
  // Clan ER Lasers
  {
    id: 'clan-er-micro-laser',
    name: 'ER Micro Laser (Clan)',
    category: WeaponCategory.ENERGY,
    subType: EnergyWeaponType.ER_LASER,
    techBase: TechBase.CLAN,
    rulesLevel: RulesLevel.STANDARD,
    damage: 2,
    heat: 1,
    ranges: { minimum: 0, short: 1, medium: 2, long: 4 },
    weight: 0.25,
    criticalSlots: 1,
    costCBills: 10000,
    battleValue: 7,
    introductionYear: 3060,
  },
  {
    id: 'clan-er-small-laser',
    name: 'ER Small Laser (Clan)',
    category: WeaponCategory.ENERGY,
    subType: EnergyWeaponType.ER_LASER,
    techBase: TechBase.CLAN,
    rulesLevel: RulesLevel.STANDARD,
    damage: 5,
    heat: 2,
    ranges: { minimum: 0, short: 2, medium: 4, long: 6 },
    weight: 0.5,
    criticalSlots: 1,
    costCBills: 11250,
    battleValue: 31,
    introductionYear: 2825,
  },
  {
    id: 'clan-er-medium-laser',
    name: 'ER Medium Laser (Clan)',
    category: WeaponCategory.ENERGY,
    subType: EnergyWeaponType.ER_LASER,
    techBase: TechBase.CLAN,
    rulesLevel: RulesLevel.STANDARD,
    damage: 7,
    heat: 5,
    ranges: { minimum: 0, short: 5, medium: 10, long: 15 },
    weight: 1,
    criticalSlots: 1,
    costCBills: 80000,
    battleValue: 108,
    introductionYear: 2824,
  },
  {
    id: 'clan-er-large-laser',
    name: 'ER Large Laser (Clan)',
    category: WeaponCategory.ENERGY,
    subType: EnergyWeaponType.ER_LASER,
    techBase: TechBase.CLAN,
    rulesLevel: RulesLevel.STANDARD,
    damage: 10,
    heat: 12,
    ranges: { minimum: 0, short: 8, medium: 15, long: 25 },
    weight: 4,
    criticalSlots: 1,
    costCBills: 200000,
    battleValue: 248,
    introductionYear: 2820,
  },
] as const;

/**
 * Pulse Lasers
 */
export const PULSE_LASERS: readonly IWeapon[] = [
  // Inner Sphere Pulse Lasers
  {
    id: 'small-pulse-laser',
    name: 'Small Pulse Laser',
    category: WeaponCategory.ENERGY,
    subType: EnergyWeaponType.PULSE_LASER,
    techBase: TechBase.INNER_SPHERE,
    rulesLevel: RulesLevel.STANDARD,
    damage: 3,
    heat: 2,
    ranges: { minimum: 0, short: 1, medium: 2, long: 3 },
    weight: 1,
    criticalSlots: 1,
    costCBills: 16000,
    battleValue: 12,
    introductionYear: 2609,
    special: ['-2 to-hit modifier'],
  },
  {
    id: 'medium-pulse-laser',
    name: 'Medium Pulse Laser',
    category: WeaponCategory.ENERGY,
    subType: EnergyWeaponType.PULSE_LASER,
    techBase: TechBase.INNER_SPHERE,
    rulesLevel: RulesLevel.STANDARD,
    damage: 6,
    heat: 4,
    ranges: { minimum: 0, short: 2, medium: 4, long: 6 },
    weight: 2,
    criticalSlots: 1,
    costCBills: 60000,
    battleValue: 48,
    introductionYear: 2609,
    special: ['-2 to-hit modifier'],
  },
  {
    id: 'large-pulse-laser',
    name: 'Large Pulse Laser',
    category: WeaponCategory.ENERGY,
    subType: EnergyWeaponType.PULSE_LASER,
    techBase: TechBase.INNER_SPHERE,
    rulesLevel: RulesLevel.STANDARD,
    damage: 9,
    heat: 10,
    ranges: { minimum: 0, short: 3, medium: 7, long: 10 },
    weight: 7,
    criticalSlots: 2,
    costCBills: 175000,
    battleValue: 119,
    introductionYear: 2609,
    special: ['-2 to-hit modifier'],
  },
  // Clan Pulse Lasers
  {
    id: 'clan-micro-pulse-laser',
    name: 'Micro Pulse Laser (Clan)',
    category: WeaponCategory.ENERGY,
    subType: EnergyWeaponType.PULSE_LASER,
    techBase: TechBase.CLAN,
    rulesLevel: RulesLevel.STANDARD,
    damage: 3,
    heat: 1,
    ranges: { minimum: 0, short: 1, medium: 2, long: 3 },
    weight: 0.5,
    criticalSlots: 1,
    costCBills: 12500,
    battleValue: 12,
    introductionYear: 3060,
    special: ['-2 to-hit modifier'],
  },
  {
    id: 'clan-small-pulse-laser',
    name: 'Small Pulse Laser (Clan)',
    category: WeaponCategory.ENERGY,
    subType: EnergyWeaponType.PULSE_LASER,
    techBase: TechBase.CLAN,
    rulesLevel: RulesLevel.STANDARD,
    damage: 3,
    heat: 2,
    ranges: { minimum: 0, short: 2, medium: 4, long: 6 },
    weight: 1,
    criticalSlots: 1,
    costCBills: 16000,
    battleValue: 24,
    introductionYear: 2829,
    special: ['-2 to-hit modifier'],
  },
  {
    id: 'clan-medium-pulse-laser',
    name: 'Medium Pulse Laser (Clan)',
    category: WeaponCategory.ENERGY,
    subType: EnergyWeaponType.PULSE_LASER,
    techBase: TechBase.CLAN,
    rulesLevel: RulesLevel.STANDARD,
    damage: 7,
    heat: 4,
    ranges: { minimum: 0, short: 4, medium: 8, long: 12 },
    weight: 2,
    criticalSlots: 1,
    costCBills: 60000,
    battleValue: 111,
    introductionYear: 2829,
    special: ['-2 to-hit modifier'],
  },
  {
    id: 'clan-large-pulse-laser',
    name: 'Large Pulse Laser (Clan)',
    category: WeaponCategory.ENERGY,
    subType: EnergyWeaponType.PULSE_LASER,
    techBase: TechBase.CLAN,
    rulesLevel: RulesLevel.STANDARD,
    damage: 10,
    heat: 10,
    ranges: { minimum: 0, short: 6, medium: 14, long: 20 },
    weight: 6,
    criticalSlots: 2,
    costCBills: 175000,
    battleValue: 265,
    introductionYear: 2829,
    special: ['-2 to-hit modifier'],
  },
] as const;

/**
 * Heavy Lasers
 */
export const HEAVY_LASERS: readonly IWeapon[] = [
  {
    id: 'small-heavy-laser',
    name: 'Small Heavy Laser (Clan)',
    category: WeaponCategory.ENERGY,
    subType: EnergyWeaponType.HEAVY_LASER,
    techBase: TechBase.CLAN,
    rulesLevel: RulesLevel.ADVANCED,
    damage: 6,
    heat: 3,
    ranges: { minimum: 0, short: 1, medium: 2, long: 3 },
    weight: 0.5,
    criticalSlots: 1,
    costCBills: 20000,
    battleValue: 15,
    introductionYear: 3059,
    special: ['+1 to-hit modifier'],
  },
  {
    id: 'medium-heavy-laser',
    name: 'Medium Heavy Laser (Clan)',
    category: WeaponCategory.ENERGY,
    subType: EnergyWeaponType.HEAVY_LASER,
    techBase: TechBase.CLAN,
    rulesLevel: RulesLevel.ADVANCED,
    damage: 10,
    heat: 7,
    ranges: { minimum: 0, short: 3, medium: 6, long: 9 },
    weight: 1,
    criticalSlots: 2,
    costCBills: 100000,
    battleValue: 76,
    introductionYear: 3059,
    special: ['+1 to-hit modifier'],
  },
  {
    id: 'large-heavy-laser',
    name: 'Large Heavy Laser (Clan)',
    category: WeaponCategory.ENERGY,
    subType: EnergyWeaponType.HEAVY_LASER,
    techBase: TechBase.CLAN,
    rulesLevel: RulesLevel.ADVANCED,
    damage: 16,
    heat: 18,
    ranges: { minimum: 0, short: 5, medium: 10, long: 15 },
    weight: 4,
    criticalSlots: 3,
    costCBills: 250000,
    battleValue: 244,
    introductionYear: 3059,
    special: ['+1 to-hit modifier'],
  },
] as const;

/**
 * PPCs
 */
export const PPCS: readonly IWeapon[] = [
  {
    id: 'ppc',
    name: 'PPC',
    category: WeaponCategory.ENERGY,
    subType: EnergyWeaponType.PPC,
    techBase: TechBase.INNER_SPHERE,
    rulesLevel: RulesLevel.INTRODUCTORY,
    damage: 10,
    heat: 10,
    ranges: { minimum: 3, short: 6, medium: 12, long: 18 },
    weight: 7,
    criticalSlots: 3,
    costCBills: 200000,
    battleValue: 176,
    introductionYear: 2460,
  },
  {
    id: 'er-ppc',
    name: 'ER PPC',
    category: WeaponCategory.ENERGY,
    subType: EnergyWeaponType.PPC,
    techBase: TechBase.INNER_SPHERE,
    rulesLevel: RulesLevel.STANDARD,
    damage: 10,
    heat: 15,
    ranges: { minimum: 0, short: 7, medium: 14, long: 23 },
    weight: 7,
    criticalSlots: 3,
    costCBills: 300000,
    battleValue: 229,
    introductionYear: 2751,
  },
  {
    id: 'light-ppc',
    name: 'Light PPC',
    category: WeaponCategory.ENERGY,
    subType: EnergyWeaponType.PPC,
    techBase: TechBase.INNER_SPHERE,
    rulesLevel: RulesLevel.STANDARD,
    damage: 5,
    heat: 5,
    ranges: { minimum: 3, short: 6, medium: 12, long: 18 },
    weight: 3,
    criticalSlots: 2,
    costCBills: 150000,
    battleValue: 88,
    introductionYear: 3067,
  },
  {
    id: 'heavy-ppc',
    name: 'Heavy PPC',
    category: WeaponCategory.ENERGY,
    subType: EnergyWeaponType.PPC,
    techBase: TechBase.INNER_SPHERE,
    rulesLevel: RulesLevel.STANDARD,
    damage: 15,
    heat: 15,
    ranges: { minimum: 3, short: 6, medium: 12, long: 18 },
    weight: 10,
    criticalSlots: 4,
    costCBills: 250000,
    battleValue: 295,
    introductionYear: 3067,
  },
  {
    id: 'snub-nose-ppc',
    name: 'Snub-Nose PPC',
    category: WeaponCategory.ENERGY,
    subType: EnergyWeaponType.PPC,
    techBase: TechBase.INNER_SPHERE,
    rulesLevel: RulesLevel.STANDARD,
    damage: 10,
    heat: 10,
    ranges: { minimum: 0, short: 5, medium: 10, long: 15 },
    weight: 6,
    criticalSlots: 2,
    costCBills: 165000,
    battleValue: 165,
    introductionYear: 3067,
  },
  {
    id: 'clan-er-ppc',
    name: 'ER PPC (Clan)',
    category: WeaponCategory.ENERGY,
    subType: EnergyWeaponType.PPC,
    techBase: TechBase.CLAN,
    rulesLevel: RulesLevel.STANDARD,
    damage: 15,
    heat: 15,
    ranges: { minimum: 0, short: 7, medium: 14, long: 23 },
    weight: 6,
    criticalSlots: 2,
    costCBills: 300000,
    battleValue: 412,
    introductionYear: 2824,
  },
] as const;

/**
 * Flamers
 */
export const FLAMERS: readonly IWeapon[] = [
  {
    id: 'flamer',
    name: 'Flamer',
    category: WeaponCategory.ENERGY,
    subType: EnergyWeaponType.FLAMER,
    techBase: TechBase.INNER_SPHERE,
    rulesLevel: RulesLevel.INTRODUCTORY,
    damage: 2,
    heat: 3,
    ranges: { minimum: 0, short: 1, medium: 2, long: 3 },
    weight: 1,
    criticalSlots: 1,
    costCBills: 7500,
    battleValue: 6,
    introductionYear: 2025,
    special: ['Causes 2 heat to target'],
  },
  {
    id: 'heavy-flamer',
    name: 'Heavy Flamer',
    category: WeaponCategory.ENERGY,
    subType: EnergyWeaponType.FLAMER,
    techBase: TechBase.INNER_SPHERE,
    rulesLevel: RulesLevel.ADVANCED,
    damage: 4,
    heat: 5,
    ranges: { minimum: 0, short: 2, medium: 3, long: 4 },
    weight: 1.5,
    criticalSlots: 1,
    costCBills: 11250,
    battleValue: 15,
    introductionYear: 3068,
    special: ['Causes 4 heat to target'],
  },
  {
    id: 'vehicle-flamer',
    name: 'Vehicle Flamer',
    category: WeaponCategory.ENERGY,
    subType: EnergyWeaponType.FLAMER,
    techBase: TechBase.INNER_SPHERE,
    rulesLevel: RulesLevel.INTRODUCTORY,
    damage: 2,
    heat: 3,
    ranges: { minimum: 0, short: 1, medium: 2, long: 3 },
    weight: 0.5,
    criticalSlots: 1,
    ammoPerTon: 20,
    costCBills: 7500,
    battleValue: 5,
    introductionYear: 1950,
    special: ['Causes 2 heat to target', 'Requires ammo'],
  },
  {
    id: 'clan-flamer',
    name: 'Flamer (Clan)',
    category: WeaponCategory.ENERGY,
    subType: EnergyWeaponType.FLAMER,
    techBase: TechBase.CLAN,
    rulesLevel: RulesLevel.STANDARD,
    damage: 2,
    heat: 3,
    ranges: { minimum: 0, short: 1, medium: 2, long: 3 },
    weight: 0.5,
    criticalSlots: 1,
    costCBills: 7500,
    battleValue: 6,
    introductionYear: 2827,
    special: ['Causes 2 heat to target'],
  },
] as const;

/**
 * Laser AMS
 */
export const LASER_AMS: readonly IWeapon[] = [
  {
    id: 'laser-ams',
    name: 'Laser Anti-Missile System',
    category: WeaponCategory.ENERGY,
    subType: EnergyWeaponType.AMS,
    techBase: TechBase.INNER_SPHERE,
    rulesLevel: RulesLevel.ADVANCED,
    damage: 0,
    heat: 7,
    ranges: { minimum: 0, short: 1, medium: 1, long: 1 },
    weight: 1.5,
    criticalSlots: 2,
    costCBills: 225000,
    battleValue: 45,
    introductionYear: 3059,
    special: ['Defensive', 'No ammo required'],
  },
  {
    id: 'clan-laser-ams',
    name: 'Laser Anti-Missile System (Clan)',
    category: WeaponCategory.ENERGY,
    subType: EnergyWeaponType.AMS,
    techBase: TechBase.CLAN,
    rulesLevel: RulesLevel.ADVANCED,
    damage: 0,
    heat: 5,
    ranges: { minimum: 0, short: 1, medium: 1, long: 1 },
    weight: 1,
    criticalSlots: 1,
    costCBills: 225000,
    battleValue: 45,
    introductionYear: 3048,
    special: ['Defensive', 'No ammo required'],
  },
] as const;

/**
 * All energy weapons combined
 */
export const ENERGY_WEAPONS: readonly IWeapon[] = [
  ...STANDARD_LASERS,
  ...ER_LASERS,
  ...PULSE_LASERS,
  ...HEAVY_LASERS,
  ...PPCS,
  ...FLAMERS,
  ...LASER_AMS,
] as const;

