/**
 * Missile Weapon Definitions
 * 
 * LRMs, SRMs, Streak, MRMs, ATMs, MMLs, and NARC systems.
 * 
 * @spec openspec/specs/weapon-system/spec.md
 */

import { TechBase } from '../../enums/TechBase';
import { RulesLevel } from '../../enums/RulesLevel';
import { IWeapon, WeaponCategory, MissileWeaponType } from './interfaces';

/**
 * Long Range Missiles
 */
export const LRM_LAUNCHERS: readonly IWeapon[] = [
  {
    id: 'lrm-5',
    name: 'LRM 5',
    category: WeaponCategory.MISSILE,
    subType: MissileWeaponType.LRM,
    techBase: TechBase.INNER_SPHERE,
    rulesLevel: RulesLevel.INTRODUCTORY,
    damage: '1/missile',
    heat: 2,
    ranges: { minimum: 6, short: 7, medium: 14, long: 21 },
    weight: 2,
    criticalSlots: 1,
    ammoPerTon: 24,
    costCBills: 30000,
    battleValue: 45,
    introductionYear: 2295,
  },
  {
    id: 'lrm-10',
    name: 'LRM 10',
    category: WeaponCategory.MISSILE,
    subType: MissileWeaponType.LRM,
    techBase: TechBase.INNER_SPHERE,
    rulesLevel: RulesLevel.INTRODUCTORY,
    damage: '1/missile',
    heat: 4,
    ranges: { minimum: 6, short: 7, medium: 14, long: 21 },
    weight: 5,
    criticalSlots: 2,
    ammoPerTon: 12,
    costCBills: 100000,
    battleValue: 90,
    introductionYear: 2295,
  },
  {
    id: 'lrm-15',
    name: 'LRM 15',
    category: WeaponCategory.MISSILE,
    subType: MissileWeaponType.LRM,
    techBase: TechBase.INNER_SPHERE,
    rulesLevel: RulesLevel.INTRODUCTORY,
    damage: '1/missile',
    heat: 5,
    ranges: { minimum: 6, short: 7, medium: 14, long: 21 },
    weight: 7,
    criticalSlots: 3,
    ammoPerTon: 8,
    costCBills: 175000,
    battleValue: 136,
    introductionYear: 2295,
  },
  {
    id: 'lrm-20',
    name: 'LRM 20',
    category: WeaponCategory.MISSILE,
    subType: MissileWeaponType.LRM,
    techBase: TechBase.INNER_SPHERE,
    rulesLevel: RulesLevel.INTRODUCTORY,
    damage: '1/missile',
    heat: 6,
    ranges: { minimum: 6, short: 7, medium: 14, long: 21 },
    weight: 10,
    criticalSlots: 5,
    ammoPerTon: 6,
    costCBills: 250000,
    battleValue: 181,
    introductionYear: 2295,
  },
  // Clan LRMs
  {
    id: 'clan-lrm-5',
    name: 'LRM 5 (Clan)',
    category: WeaponCategory.MISSILE,
    subType: MissileWeaponType.LRM,
    techBase: TechBase.CLAN,
    rulesLevel: RulesLevel.STANDARD,
    damage: '1/missile',
    heat: 2,
    ranges: { minimum: 0, short: 7, medium: 14, long: 21 },
    weight: 1,
    criticalSlots: 1,
    ammoPerTon: 24,
    costCBills: 30000,
    battleValue: 55,
    introductionYear: 2824,
  },
  {
    id: 'clan-lrm-10',
    name: 'LRM 10 (Clan)',
    category: WeaponCategory.MISSILE,
    subType: MissileWeaponType.LRM,
    techBase: TechBase.CLAN,
    rulesLevel: RulesLevel.STANDARD,
    damage: '1/missile',
    heat: 4,
    ranges: { minimum: 0, short: 7, medium: 14, long: 21 },
    weight: 2.5,
    criticalSlots: 1,
    ammoPerTon: 12,
    costCBills: 100000,
    battleValue: 109,
    introductionYear: 2824,
  },
  {
    id: 'clan-lrm-15',
    name: 'LRM 15 (Clan)',
    category: WeaponCategory.MISSILE,
    subType: MissileWeaponType.LRM,
    techBase: TechBase.CLAN,
    rulesLevel: RulesLevel.STANDARD,
    damage: '1/missile',
    heat: 5,
    ranges: { minimum: 0, short: 7, medium: 14, long: 21 },
    weight: 3.5,
    criticalSlots: 2,
    ammoPerTon: 8,
    costCBills: 175000,
    battleValue: 164,
    introductionYear: 2824,
  },
  {
    id: 'clan-lrm-20',
    name: 'LRM 20 (Clan)',
    category: WeaponCategory.MISSILE,
    subType: MissileWeaponType.LRM,
    techBase: TechBase.CLAN,
    rulesLevel: RulesLevel.STANDARD,
    damage: '1/missile',
    heat: 6,
    ranges: { minimum: 0, short: 7, medium: 14, long: 21 },
    weight: 5,
    criticalSlots: 4,
    ammoPerTon: 6,
    costCBills: 250000,
    battleValue: 220,
    introductionYear: 2824,
  },
] as const;

/**
 * Short Range Missiles
 */
export const SRM_LAUNCHERS: readonly IWeapon[] = [
  {
    id: 'srm-2',
    name: 'SRM 2',
    category: WeaponCategory.MISSILE,
    subType: MissileWeaponType.SRM,
    techBase: TechBase.INNER_SPHERE,
    rulesLevel: RulesLevel.INTRODUCTORY,
    damage: '2/missile',
    heat: 2,
    ranges: { minimum: 0, short: 3, medium: 6, long: 9 },
    weight: 1,
    criticalSlots: 1,
    ammoPerTon: 50,
    costCBills: 10000,
    battleValue: 21,
    introductionYear: 2370,
  },
  {
    id: 'srm-4',
    name: 'SRM 4',
    category: WeaponCategory.MISSILE,
    subType: MissileWeaponType.SRM,
    techBase: TechBase.INNER_SPHERE,
    rulesLevel: RulesLevel.INTRODUCTORY,
    damage: '2/missile',
    heat: 3,
    ranges: { minimum: 0, short: 3, medium: 6, long: 9 },
    weight: 2,
    criticalSlots: 1,
    ammoPerTon: 25,
    costCBills: 60000,
    battleValue: 39,
    introductionYear: 2370,
  },
  {
    id: 'srm-6',
    name: 'SRM 6',
    category: WeaponCategory.MISSILE,
    subType: MissileWeaponType.SRM,
    techBase: TechBase.INNER_SPHERE,
    rulesLevel: RulesLevel.INTRODUCTORY,
    damage: '2/missile',
    heat: 4,
    ranges: { minimum: 0, short: 3, medium: 6, long: 9 },
    weight: 3,
    criticalSlots: 2,
    ammoPerTon: 15,
    costCBills: 80000,
    battleValue: 59,
    introductionYear: 2370,
  },
  // Clan SRMs
  {
    id: 'clan-srm-2',
    name: 'SRM 2 (Clan)',
    category: WeaponCategory.MISSILE,
    subType: MissileWeaponType.SRM,
    techBase: TechBase.CLAN,
    rulesLevel: RulesLevel.STANDARD,
    damage: '2/missile',
    heat: 2,
    ranges: { minimum: 0, short: 3, medium: 6, long: 9 },
    weight: 0.5,
    criticalSlots: 1,
    ammoPerTon: 50,
    costCBills: 10000,
    battleValue: 21,
    introductionYear: 2824,
  },
  {
    id: 'clan-srm-4',
    name: 'SRM 4 (Clan)',
    category: WeaponCategory.MISSILE,
    subType: MissileWeaponType.SRM,
    techBase: TechBase.CLAN,
    rulesLevel: RulesLevel.STANDARD,
    damage: '2/missile',
    heat: 3,
    ranges: { minimum: 0, short: 3, medium: 6, long: 9 },
    weight: 1,
    criticalSlots: 1,
    ammoPerTon: 25,
    costCBills: 60000,
    battleValue: 39,
    introductionYear: 2824,
  },
  {
    id: 'clan-srm-6',
    name: 'SRM 6 (Clan)',
    category: WeaponCategory.MISSILE,
    subType: MissileWeaponType.SRM,
    techBase: TechBase.CLAN,
    rulesLevel: RulesLevel.STANDARD,
    damage: '2/missile',
    heat: 4,
    ranges: { minimum: 0, short: 3, medium: 6, long: 9 },
    weight: 1.5,
    criticalSlots: 1,
    ammoPerTon: 15,
    costCBills: 80000,
    battleValue: 59,
    introductionYear: 2824,
  },
] as const;

/**
 * Streak SRM Launchers
 */
export const STREAK_LAUNCHERS: readonly IWeapon[] = [
  {
    id: 'streak-srm-2',
    name: 'Streak SRM 2',
    category: WeaponCategory.MISSILE,
    subType: MissileWeaponType.STREAK_SRM,
    techBase: TechBase.INNER_SPHERE,
    rulesLevel: RulesLevel.STANDARD,
    damage: '2/missile',
    heat: 2,
    ranges: { minimum: 0, short: 3, medium: 6, long: 9 },
    weight: 1.5,
    criticalSlots: 1,
    ammoPerTon: 50,
    costCBills: 15000,
    battleValue: 30,
    introductionYear: 2647,
    special: ['No ammo wasted on miss'],
  },
  {
    id: 'streak-srm-4',
    name: 'Streak SRM 4',
    category: WeaponCategory.MISSILE,
    subType: MissileWeaponType.STREAK_SRM,
    techBase: TechBase.INNER_SPHERE,
    rulesLevel: RulesLevel.STANDARD,
    damage: '2/missile',
    heat: 3,
    ranges: { minimum: 0, short: 3, medium: 6, long: 9 },
    weight: 3,
    criticalSlots: 1,
    ammoPerTon: 25,
    costCBills: 90000,
    battleValue: 59,
    introductionYear: 3058,
    special: ['No ammo wasted on miss'],
  },
  {
    id: 'streak-srm-6',
    name: 'Streak SRM 6',
    category: WeaponCategory.MISSILE,
    subType: MissileWeaponType.STREAK_SRM,
    techBase: TechBase.INNER_SPHERE,
    rulesLevel: RulesLevel.STANDARD,
    damage: '2/missile',
    heat: 4,
    ranges: { minimum: 0, short: 3, medium: 6, long: 9 },
    weight: 4.5,
    criticalSlots: 2,
    ammoPerTon: 15,
    costCBills: 120000,
    battleValue: 89,
    introductionYear: 3058,
    special: ['No ammo wasted on miss'],
  },
  // Clan Streak SRMs
  {
    id: 'clan-streak-srm-2',
    name: 'Streak SRM 2 (Clan)',
    category: WeaponCategory.MISSILE,
    subType: MissileWeaponType.STREAK_SRM,
    techBase: TechBase.CLAN,
    rulesLevel: RulesLevel.STANDARD,
    damage: '2/missile',
    heat: 2,
    ranges: { minimum: 0, short: 4, medium: 8, long: 12 },
    weight: 1,
    criticalSlots: 1,
    ammoPerTon: 50,
    costCBills: 15000,
    battleValue: 40,
    introductionYear: 2826,
    special: ['No ammo wasted on miss'],
  },
  {
    id: 'clan-streak-srm-4',
    name: 'Streak SRM 4 (Clan)',
    category: WeaponCategory.MISSILE,
    subType: MissileWeaponType.STREAK_SRM,
    techBase: TechBase.CLAN,
    rulesLevel: RulesLevel.STANDARD,
    damage: '2/missile',
    heat: 3,
    ranges: { minimum: 0, short: 4, medium: 8, long: 12 },
    weight: 2,
    criticalSlots: 1,
    ammoPerTon: 25,
    costCBills: 90000,
    battleValue: 79,
    introductionYear: 2826,
    special: ['No ammo wasted on miss'],
  },
  {
    id: 'clan-streak-srm-6',
    name: 'Streak SRM 6 (Clan)',
    category: WeaponCategory.MISSILE,
    subType: MissileWeaponType.STREAK_SRM,
    techBase: TechBase.CLAN,
    rulesLevel: RulesLevel.STANDARD,
    damage: '2/missile',
    heat: 4,
    ranges: { minimum: 0, short: 4, medium: 8, long: 12 },
    weight: 3,
    criticalSlots: 2,
    ammoPerTon: 15,
    costCBills: 120000,
    battleValue: 118,
    introductionYear: 2826,
    special: ['No ammo wasted on miss'],
  },
] as const;

/**
 * MRM Launchers
 */
export const MRM_LAUNCHERS: readonly IWeapon[] = [
  {
    id: 'mrm-10',
    name: 'MRM 10',
    category: WeaponCategory.MISSILE,
    subType: MissileWeaponType.MRM,
    techBase: TechBase.INNER_SPHERE,
    rulesLevel: RulesLevel.STANDARD,
    damage: '1/missile',
    heat: 4,
    ranges: { minimum: 0, short: 3, medium: 8, long: 15 },
    weight: 3,
    criticalSlots: 2,
    ammoPerTon: 24,
    costCBills: 50000,
    battleValue: 56,
    introductionYear: 3058,
    special: ['+1 to-hit penalty'],
  },
  {
    id: 'mrm-20',
    name: 'MRM 20',
    category: WeaponCategory.MISSILE,
    subType: MissileWeaponType.MRM,
    techBase: TechBase.INNER_SPHERE,
    rulesLevel: RulesLevel.STANDARD,
    damage: '1/missile',
    heat: 6,
    ranges: { minimum: 0, short: 3, medium: 8, long: 15 },
    weight: 7,
    criticalSlots: 3,
    ammoPerTon: 12,
    costCBills: 125000,
    battleValue: 112,
    introductionYear: 3058,
    special: ['+1 to-hit penalty'],
  },
  {
    id: 'mrm-30',
    name: 'MRM 30',
    category: WeaponCategory.MISSILE,
    subType: MissileWeaponType.MRM,
    techBase: TechBase.INNER_SPHERE,
    rulesLevel: RulesLevel.STANDARD,
    damage: '1/missile',
    heat: 10,
    ranges: { minimum: 0, short: 3, medium: 8, long: 15 },
    weight: 10,
    criticalSlots: 5,
    ammoPerTon: 8,
    costCBills: 225000,
    battleValue: 168,
    introductionYear: 3058,
    special: ['+1 to-hit penalty'],
  },
  {
    id: 'mrm-40',
    name: 'MRM 40',
    category: WeaponCategory.MISSILE,
    subType: MissileWeaponType.MRM,
    techBase: TechBase.INNER_SPHERE,
    rulesLevel: RulesLevel.STANDARD,
    damage: '1/missile',
    heat: 12,
    ranges: { minimum: 0, short: 3, medium: 8, long: 15 },
    weight: 12,
    criticalSlots: 7,
    ammoPerTon: 6,
    costCBills: 350000,
    battleValue: 224,
    introductionYear: 3058,
    special: ['+1 to-hit penalty'],
  },
] as const;

/**
 * ATM Launchers (Clan only)
 */
export const ATM_LAUNCHERS: readonly IWeapon[] = [
  {
    id: 'atm-3',
    name: 'ATM 3',
    category: WeaponCategory.MISSILE,
    subType: MissileWeaponType.ATM,
    techBase: TechBase.CLAN,
    rulesLevel: RulesLevel.STANDARD,
    damage: '2/missile',
    heat: 2,
    ranges: { minimum: 4, short: 5, medium: 10, long: 15 },
    weight: 1.5,
    criticalSlots: 2,
    ammoPerTon: 20,
    costCBills: 50000,
    battleValue: 53,
    introductionYear: 3054,
    special: ['Multiple ammo types'],
  },
  {
    id: 'atm-6',
    name: 'ATM 6',
    category: WeaponCategory.MISSILE,
    subType: MissileWeaponType.ATM,
    techBase: TechBase.CLAN,
    rulesLevel: RulesLevel.STANDARD,
    damage: '2/missile',
    heat: 4,
    ranges: { minimum: 4, short: 5, medium: 10, long: 15 },
    weight: 3.5,
    criticalSlots: 3,
    ammoPerTon: 10,
    costCBills: 125000,
    battleValue: 105,
    introductionYear: 3054,
    special: ['Multiple ammo types'],
  },
  {
    id: 'atm-9',
    name: 'ATM 9',
    category: WeaponCategory.MISSILE,
    subType: MissileWeaponType.ATM,
    techBase: TechBase.CLAN,
    rulesLevel: RulesLevel.STANDARD,
    damage: '2/missile',
    heat: 6,
    ranges: { minimum: 4, short: 5, medium: 10, long: 15 },
    weight: 5,
    criticalSlots: 4,
    ammoPerTon: 7,
    costCBills: 225000,
    battleValue: 147,
    introductionYear: 3054,
    special: ['Multiple ammo types'],
  },
  {
    id: 'atm-12',
    name: 'ATM 12',
    category: WeaponCategory.MISSILE,
    subType: MissileWeaponType.ATM,
    techBase: TechBase.CLAN,
    rulesLevel: RulesLevel.STANDARD,
    damage: '2/missile',
    heat: 8,
    ranges: { minimum: 4, short: 5, medium: 10, long: 15 },
    weight: 7,
    criticalSlots: 5,
    ammoPerTon: 5,
    costCBills: 350000,
    battleValue: 212,
    introductionYear: 3054,
    special: ['Multiple ammo types'],
  },
] as const;

/**
 * MML Launchers
 */
export const MML_LAUNCHERS: readonly IWeapon[] = [
  {
    id: 'mml-3',
    name: 'MML 3',
    category: WeaponCategory.MISSILE,
    subType: MissileWeaponType.MML,
    techBase: TechBase.INNER_SPHERE,
    rulesLevel: RulesLevel.STANDARD,
    damage: '1-2/missile',
    heat: 2,
    ranges: { minimum: 0, short: 3, medium: 6, long: 9 },
    weight: 1.5,
    criticalSlots: 2,
    ammoPerTon: 40,
    costCBills: 45000,
    battleValue: 29,
    introductionYear: 3068,
    special: ['Can fire LRM or SRM ammo'],
  },
  {
    id: 'mml-5',
    name: 'MML 5',
    category: WeaponCategory.MISSILE,
    subType: MissileWeaponType.MML,
    techBase: TechBase.INNER_SPHERE,
    rulesLevel: RulesLevel.STANDARD,
    damage: '1-2/missile',
    heat: 3,
    ranges: { minimum: 0, short: 3, medium: 6, long: 9 },
    weight: 3,
    criticalSlots: 3,
    ammoPerTon: 24,
    costCBills: 75000,
    battleValue: 45,
    introductionYear: 3068,
    special: ['Can fire LRM or SRM ammo'],
  },
  {
    id: 'mml-7',
    name: 'MML 7',
    category: WeaponCategory.MISSILE,
    subType: MissileWeaponType.MML,
    techBase: TechBase.INNER_SPHERE,
    rulesLevel: RulesLevel.STANDARD,
    damage: '1-2/missile',
    heat: 4,
    ranges: { minimum: 0, short: 3, medium: 6, long: 9 },
    weight: 4.5,
    criticalSlots: 4,
    ammoPerTon: 17,
    costCBills: 105000,
    battleValue: 67,
    introductionYear: 3068,
    special: ['Can fire LRM or SRM ammo'],
  },
  {
    id: 'mml-9',
    name: 'MML 9',
    category: WeaponCategory.MISSILE,
    subType: MissileWeaponType.MML,
    techBase: TechBase.INNER_SPHERE,
    rulesLevel: RulesLevel.STANDARD,
    damage: '1-2/missile',
    heat: 5,
    ranges: { minimum: 0, short: 3, medium: 6, long: 9 },
    weight: 6,
    criticalSlots: 5,
    ammoPerTon: 13,
    costCBills: 125000,
    battleValue: 86,
    introductionYear: 3068,
    special: ['Can fire LRM or SRM ammo'],
  },
] as const;

/**
 * NARC/iNARC
 */
export const NARC_LAUNCHERS: readonly IWeapon[] = [
  {
    id: 'narc',
    name: 'NARC Missile Beacon',
    category: WeaponCategory.MISSILE,
    subType: MissileWeaponType.NARC,
    techBase: TechBase.INNER_SPHERE,
    rulesLevel: RulesLevel.STANDARD,
    damage: 0,
    heat: 0,
    ranges: { minimum: 0, short: 3, medium: 6, long: 9 },
    weight: 3,
    criticalSlots: 2,
    ammoPerTon: 6,
    costCBills: 100000,
    battleValue: 30,
    introductionYear: 2587,
    special: ['Homing beacon'],
    isExplosive: true,
  },
  {
    id: 'inarc',
    name: 'iNARC Launcher',
    category: WeaponCategory.MISSILE,
    subType: MissileWeaponType.INARC,
    techBase: TechBase.INNER_SPHERE,
    rulesLevel: RulesLevel.STANDARD,
    damage: 0,
    heat: 0,
    ranges: { minimum: 0, short: 4, medium: 9, long: 15 },
    weight: 5,
    criticalSlots: 3,
    ammoPerTon: 4,
    costCBills: 250000,
    battleValue: 75,
    introductionYear: 3062,
    special: ['Multiple pod types'],
    isExplosive: true,
  },
  {
    id: 'clan-narc',
    name: 'NARC Missile Beacon (Clan)',
    category: WeaponCategory.MISSILE,
    subType: MissileWeaponType.NARC,
    techBase: TechBase.CLAN,
    rulesLevel: RulesLevel.STANDARD,
    damage: 0,
    heat: 0,
    ranges: { minimum: 0, short: 4, medium: 8, long: 12 },
    weight: 2,
    criticalSlots: 1,
    ammoPerTon: 6,
    costCBills: 100000,
    battleValue: 30,
    introductionYear: 2831,
    special: ['Homing beacon'],
    isExplosive: true,
  },
] as const;

/**
 * All missile weapons combined
 */
export const MISSILE_WEAPONS: readonly IWeapon[] = [
  ...LRM_LAUNCHERS,
  ...SRM_LAUNCHERS,
  ...STREAK_LAUNCHERS,
  ...MRM_LAUNCHERS,
  ...ATM_LAUNCHERS,
  ...MML_LAUNCHERS,
  ...NARC_LAUNCHERS,
] as const;

